export const credentials = {
  sauceDemoUrl: 'https://www.saucedemo.com',
  sauceDemoSubmitUniverseUrl:
    'https://events.backtrace.io/api/unique-events/submit?universe=UNIVERSE&token=TOKEN',
  sauceDemoSummedEventsUrl:
    'https://events.backtrace.io/api/summed-events/submit?universe=UNIVERSE&token=TOKEN',
  sauceDemoTitle: 'Products',
  sauceCheckoutTitle: 'Checkout: Overview',
  sauceInventoryItems: [
    'Sauce Labs Backpack',
    'Sauce Labs Bike Light',
    'Sauce Labs Bolt T-Shirt',
    'Sauce Labs Fleece Jacket',
    'Sauce Labs Onesie',
    'Test.allTheThings() T-Shirt (Red)',
  ],
  sauceInventoryItemsPrices: [
    '$29.99',
    '$9.99',
    '$15.99',
    '$49.99',
    '$7.99',
    '$15.99',
  ],
  sauceFirstName: 'Zakir',
  sauceLastName: 'Kalayci',
  sauceZipCode: '12345',
  sauceCard: 'SauceCard #31337',
  sauceShippingInfo: 'Free Pony Express Delivery!',
  sauseTotalPrice: 'Total: $10.79',
  sauceCheckoutCompleteTitle: 'Thank you for your order!',
  fakerBaseUrl: 'https://fakerapi.it/api/v1',
  pokeBaseUrl: 'https://beta.pokeapi.co/graphql/v1beta',
  token: 'abcdefgh',
  apolloUrl: '/dummyPath',
  gridPath: '/dummyPath',
  grid1: '/dummyPath',
  grid2: '/dummyPath',
}
